name: release

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types: [published]

jobs:
  docker-image:
    name: Build and push docker image (hydra - ${{ matrix.hydra-version }}, light - ${{ matrix.light }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        hydra-version:
          - '9.0'
          - '9.1'
        light:
          - 'false'
          - 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Make docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin &> /dev/null

      - name: Build docker image (basic)
        if: matrix.light == 'false'
        run: |
          docker build \
            -f ./Dockerfile \
            --build-arg "HYDRA_VER=${{ matrix.hydra-version }}" \
            --tag "tarampampam/hydra:${{ matrix.hydra-version }}" \
            .

      - name: Build docker image (light)
        if: matrix.light == 'true'
        run: |
          docker build \
            -f ./Dockerfile \
            --build-arg "HYDRA_VER=${{ matrix.hydra-version }}" \
            --build-arg "SECLIST_VER=null" \
            --tag "tarampampam/hydra:${{ matrix.hydra-version }}-light" \
            .

      - name: Push docker image (basic)
        if: matrix.light == 'false'
        run: docker push "tarampampam/hydra:${{ matrix.hydra-version }}"

      - name: Push docker image (light)
        if: matrix.light == 'true'
        run: docker push "tarampampam/hydra:${{ matrix.hydra-version }}-light"
