name: release

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types: [published]

jobs:
  docker-image:
    name: Build and push docker image (hydra v${{ matrix.hydra-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        hydra-version:
          - '9.0'
          - '9.1'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Make docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin &> /dev/null

      - name: Build docker image
        run: |
          docker build \
            -f ./Dockerfile \
            --build-arg "HYDRA_VER=${{ matrix.hydra-version }}" \
            --tag "tarampampam/hydra:${{ matrix.hydra-version }}" \
            .

      - name: Push version image
        run: docker push "tarampampam/hydra:${{ matrix.hydra-version }}"
