name: tests

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs: # Docs: <https://git.io/JvxXE>
  docker-build:
    name: Build docker image (hydra - ${{ matrix.hydra-version }}, light - ${{ matrix.light }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        hydra-version:
          - '9.0'
          - '9.1'
        light:
          - 'false'
          - 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull image for using as a cache
        run: docker pull "tarampampam/hydra:${{ matrix.hydra-version }}" || true

      - name: Build docker image (basic)
        if: matrix.light == 'false'
        run: |
          docker build \
            -f ./Dockerfile \
            --cache-from "tarampampam/hydra:${{ matrix.hydra-version }}" \
            --build-arg "HYDRA_VER=${{ matrix.hydra-version }}" \
            --tag "hydra:${{ matrix.hydra-version }}" \
            .

      - name: Build docker image (light)
        if: matrix.light == 'true'
        run: |
          docker build \
            -f ./Dockerfile \
            --cache-from "tarampampam/hydra:${{ matrix.hydra-version }}" \
            --build-arg "HYDRA_VER=${{ matrix.hydra-version }}" \
            --build-arg "SECLIST_VER=" \
            --tag "hydra:${{ matrix.hydra-version }}" \
            .

      - name: Show image info
        run: |
          docker images hydra:${{ matrix.hydra-version }}
          docker inspect hydra:${{ matrix.hydra-version }}

      - name: Try to run (with errors ignoring)
        run: docker run --rm hydra:${{ matrix.hydra-version }} -h || true
