name: tests

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs: # Docs: <https://git.io/JvxXE>
  docker-build:
    name: Build docker image (hydra v${{ matrix.hydra-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        hydra-version:
          - '9.0'
          - '9.1'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull image for using as a cache
        run: docker pull "tarampampam/hydra:${{ matrix.hydra-version }}" || true

      - name: Build docker image
        run: |
          docker build \
            -f ./Dockerfile \
            --cache-from "tarampampam/hydra:${{ matrix.hydra-version }}" \
            --build-arg "HYDRA_VER=${{ matrix.hydra-version }}" \
            --tag "hydra:${{ matrix.hydra-version }}" \
            .

      - name: Try to run (with errors ignoring)
        run: docker run --rm hydra:${{ matrix.hydra-version }} -h || true
